IOMMU group module
harvester/pcidevices pull request #30
Opened 2022-10-31 21:24 UTC by tlehman

# Summary
The issue below happens because being able to claim PCI Devices themselves can sometimes be too granular. There is a kernel grouping called an IOMMU group, and, for example, a GPU with an Audio device on the card will belong to the same iommu group. But if you claim just the GPU and not the audio device, then attaching it to a VM will fail. The devices have to be claimed in a group. The first step to enforcing this in the code is adding the iommu group number (an `int`) to the `PCIDevice` CRD.

# Issues 
- https://github.com/harvester/pcidevices/issues/29

2022-11-01 07:53 UTC, eliaskoromilas commented on pkg/iommu/go.mod
> +module github.com/harvester/pcidevices/iommu
We don't need a new module here. Just introduce it as a sub-package `"github.com/harvester/pcidevices/pkg/iommu"` (also the module path differs from it's github path, making it hard for external packages to import it).

If we are not confident (yet) exposing it as a package, we can put it under `"github.com/harvester/pcidevices/internal"`.

2022-11-07 11:04 UTC, eliaskoromilas commented
Looks good!

2022-11-16 01:07 UTC, futuretea commented on pkg/iommu/iommu.go
> +	iommuGroups, err := ioutil.ReadDir("/sys/kernel/iommu_groups")
It would be better to use a constant for `/sys/kernel/iommu_groups`

2022-11-16 01:07 UTC, futuretea commented on pkg/iommu/iommu.go
> +		group := GroupForPCIDevice(address, groupPaths)
The nested for loop can be optimized by scaning groupPaths once and save the information into a map

2022-11-18 03:25 UTC, ibrokethecloud commented on pkg/iommu/iommu.go
> +			continue
we should return error. This can then be logged and handled by the reconcilePCIDevices controller group.

2022-11-18 03:25 UTC, ibrokethecloud commented on pkg/iommu/iommu.go
> +			if err != nil {
we should change method signature to return error and let reconcile loop handle the same

2022-12-07 02:30 UTC, tlehman commented
Updated and please re-review it again

2022-12-08 20:09 UTC, eliaskoromilas requested changes

2022-12-08 20:09 UTC, eliaskoromilas commented on pkg/apis/devices.harvesterhci.io/v1beta1/pcidevice.go
> +	}
```suggestion
	if iommuGroup, err := device_manager.Handler.GetDeviceIOMMUGroup(pciBasePath, dev.Address); err == nil {
		status.IOMMUGroup = iommuGroup
	}
```

2022-12-08 20:09 UTC, eliaskoromilas commented on pkg/apis/devices.harvesterhci.io/v1beta1/pcidevice.go
> +func (status *PCIDeviceStatus) Update(dev *pci.Device, hostname string, iommuGroups map[string]int) {
```suggestion
func (status *PCIDeviceStatus) Update(dev *pci.Device, hostname string) {
```

2022-12-08 20:09 UTC, eliaskoromilas commented on pkg/apis/devices.harvesterhci.io/v1beta1/pcidevice.go
> +	}
```go
import device_manager "kubevirt.io/kubevirt/pkg/virt-handler/device-manager"

const pciBasePath = "/sys/bus/pci/devices"
```

2022-12-08 20:14 UTC, eliaskoromilas commented on pkg/apis/devices.harvesterhci.io/v1beta1/pcidevice.go
> +	}
I suggest switching to KubeVirt's `DeviceHandler` and drop our `iommu` package entirely.

2022-12-08 20:19 UTC, eliaskoromilas commented on pkg/apis/devices.harvesterhci.io/v1beta1/pcidevice.go
> +	"strconv"
```suggestion
```

2022-12-08 20:20 UTC, eliaskoromilas requested changes

2022-12-08 20:20 UTC, eliaskoromilas commented on pkg/controller/pcidevice/pcidevice_controller.go
> +		devCopy.Status.Update(dev, nodename, iommuGroupMap) // update the in-memory CR with the current PCI info
```suggestion
		devCopy.Status.Update(dev, nodename) // update the in-memory CR with the current PCI info
```

2022-12-08 20:20 UTC, eliaskoromilas commented on pkg/controller/pcidevice/pcidevice_controller.go
> +	iommuGroupMap := iommu.GroupMapForPCIDevices(iommuGroupPaths)
```suggestion
```

2022-12-08 20:20 UTC, eliaskoromilas commented on pkg/controller/pcidevice/pcidevice_controller.go
> +
```suggestion
```

2022-12-14 17:08 UTC, tlehman commented
Updated and please re-review

2022-12-14 17:14 UTC, eliaskoromilas commented
Is `github.com/harvester/pcidevices/pkg/iommu` being used? Shouldn't we drop it?

2022-12-14 21:32 UTC, tlehman commented
> Is `github.com/harvester/pcidevices/pkg/iommu` being used? Shouldn't we drop it?

I don't think so, pushing new revision after I remove it and test it

2022-12-15 12:45 UTC, eliaskoromilas commented on pkg/apis/devices.harvesterhci.io/v1beta1/pcidevice.go
> +	if iommuGroup, err := device_manager.Handler.GetDeviceIOMMUGroup(pciBasePath, dev.Address); err == nil {
Uh-oh, this will SIGSEGV without: https://github.com/kubevirt/kubevirt/blob/v0.54.0/pkg/virt-handler/device-manager/common.go#L198-L202

2022-12-15 12:45 UTC, eliaskoromilas commented on pkg/apis/devices.harvesterhci.io/v1beta1/pcidevice.go
> +
```suggestion

func init() {
	if device_manager.Handler == nil {
		device_manager.Handler = &device_manager.DeviceUtilsHandler{}
	}
}
```

2022-12-15 17:29 UTC, eliaskoromilas commented on pkg/apis/devices.harvesterhci.io/v1beta1/pcidevice.go
> +	if iommuGroup, err := device_manager.Handler.GetDeviceIOMMUGroup(pciBasePath, dev.Address); err == nil {
https://github.com/harvester/pcidevices/pull/30#discussion_r1049598061 fixes it

2023-01-13 01:09 UTC, tlehman commented
Updated: please re-review

2023-02-07 00:12 UTC, tlehman commented
Folded this commit into #35

2023-02-07 00:12 UTC, closed without merging